### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by milotype**
Sorry, it seems I did not send the German translation for metadata ... so here it is!

### CODE REVIEW

**Review by enricocid — APPROVED** [review]

**Comment by enricocid** [comment]
No problem :)

**Comment by milotype** [comment]
@enricocid Please don't forget to release German and Croatian translation of the app from Weblate. Implementing updated/new translations could probably be automated (instantly, hourly, daily/nightly, weekly, monthly, or whatever is possible with Weblate).

I'm no programmer, and I don't know your update policy, so please excuse, if my comment is unnecessary ...

**Comment by enricocid** [comment]
> @enricocid Please don't forget to release German and Croatian translation of the app from Weblate. Implementing updated/new translations could probably be automated (instantly, hourly, daily/nightly, weekly, monthly, or whatever is possible with Weblate).
> 
> I'm no programmer, and I don't know your update policy, so please excuse, if my comment is unnecessary ...

You're welcome :)
Yes, I will add new components to manage fastlane translations. I'm actually working on music player go, but I will update playstore description later today and add the componets asap :)

**Comment by enricocid** [comment]
@milotype 
Just updated the PlayStore page.
In the future I will integrate weblate to fully automate translations as You requested ;) 

Thanks again

**Pull request merged**
